Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
#  config.vm.network "public_network", bridge: "wlp58s0"
  config.vm.network "forwarded_port", guest: 82, host: 82, host_ip: "127.0.0.1"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "nginx82-vm"
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "nginx82.yaml"
  end

end