---
- name: Configure GitLab Runner
  hosts: runner
  become: true

  vars:
    runner_description: "aws-step3-runner"
    runner_tags: "docker,dind,proxmox"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - docker.io
          - curl
        state: present

    - name: Enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add GitLab Runner repository
      shell: |
        curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | bash
      args:
        creates: /etc/apt/sources.list.d/runner_gitlab-runner.list

    - name: Install GitLab Runner
      apt:
        name: gitlab-runner
        state: present
        update_cache: yes

    - name: Add gitlab-runner user to docker group
      user:
        name: gitlab-runner
        groups: docker
        append: yes

    - name: Create runner in GitLab
      uri:
        url: "{{ hostvars[groups['gitlab'][0]].gitlab_url }}/api/v4/user/runners"
        method: POST
        headers:
          PRIVATE-TOKEN: "{{ hostvars[groups['gitlab'][0]].gitlab_api_token }}"
        body_format: form-urlencoded
        body:
          runner_type: "instance_type"
          description: "{{ runner_description }}"
          tag_list: "{{ runner_tags }}"
          run_untagged: "false"
        status_code: 201
      register: runner_create
      no_log: true

    - name: Register GitLab Runner
      command: >
        gitlab-runner register
        --non-interactive
        --url "{{ hostvars[groups['gitlab'][0]].gitlab_url }}"
        --token "{{ runner_create.json.token }}"
        --executor "docker"
        --docker-image "docker:28"
      no_log: true

    - name: Enable privileged mode
      replace:
        path: /etc/gitlab-runner/config.toml
        regexp: 'privileged = false'
        replace: 'privileged = true'

    - name: Restart GitLab Runner
      systemd:
        name: gitlab-runner
        state: restarted
        enabled: yes
